BP/BA/urls.py
from django.urls import path
from . import views
app_name = 'BA'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

urlpatterns += [
    path('editing_profile/', views.editing_profile_view, name='editing_profile'),
    path('profile/', views.profile_view, name='profile'),
    path('delete_profile/', views.delete_profile_view, name='delete_profile'),
]

urlpatterns += [
    path('create_post/', views.create_post_view, name='create_post'),
    path('like_post/<int:post_id>/', views.like_post_view, name='like_post'),
    path('my_posts/', views.my_posts, name='my_posts'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('post/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('comment/edit/<int:comment_id>/', views.edit_comment, name='edit_comment'),
    path('comment/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
]

BP/BP/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import include
from django.urls import path
urlpatterns += [
    path('BA/', include('BA.urls', namespace='BA')),
]


from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/BA/', permanent=True)),
]

urlpatterns += [
path('accounts/', include('django.contrib.auth.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BP/BA/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import AbstractUser
import re
class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=150, blank=False, verbose_name='Имя')
    last_name = models.CharField(max_length=150, blank=False, verbose_name='Фамилия')
    username = models.CharField(max_length=150, unique=True, blank=False, verbose_name='Логин')
    email = models.EmailField(unique=True, blank=False, verbose_name='Электронная почта')
    middle_name = models.CharField(max_length=150, blank=False, verbose_name='Отчество')
    password1 = models.CharField(max_length=128, blank=False, null=True, verbose_name='Пароль')
    password2 = models.CharField(max_length=128, blank=False, null=True, verbose_name='Повтор пароля')
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True, verbose_name='Аватар')
    bio = models.TextField(blank=True, verbose_name='Биография')

    def clean(self):
        super().clean()
        if not re.match(r'^[А-Яа-яЁёs-]*$', self.last_name):
            raise ValidationError('Фамилия должна содержать только кириллические буквы, пробелы и дефисы.')
        if not re.match(r'^[А-Яа-яЁёs-]*$', self.first_name):
            raise ValidationError('Имя должно содержать только кириллические буквы, пробелы и дефисы.')
        if self.middle_name and not re.match(r'^[А-Яа-яЁёs-]*$', self.middle_name):
            raise ValidationError('Отчество должно содержать только кириллические буквы, пробелы и дефисы.')



from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, verbose_name='Название')
    content = models.TextField(verbose_name='Контент')
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)

    def __str__(self):
        return self.title

    @property
    def comment_count(self):
        return self.comments.count()

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(verbose_name='Комментарий')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Комментарий от {self.author.username} к посту {self.post.title}'

BP/BA/forms.py
from django import forms
from .models import CustomUser
class CustomUserCreationForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('last_name', 'first_name', 'middle_name', 'username', 'email', 'password1', 'password2', 'avatar', 'bio')



from django.contrib.auth.forms import AuthenticationForm
class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']



class UserProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('last_name', 'first_name', 'middle_name', 'username', 'avatar', 'bio')



from .models import Post
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']



from .models import Comment
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

BP/BA/views.py
# Главная страница:
from django.core.paginator import Paginator
from .models import Post
def index(request):
    posts = Post.objects.all().order_by('-created_at')
    paginator = Paginator(posts, 50)  # 50 постов на странице
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'index.html', {'page_obj': page_obj})



# Редактирование профиля:
from .forms import UserProfileForm
from django.contrib.auth.decorators import login_required
@login_required
def editing_profile_view(request):
    user = request.user
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('BA:profile')
    else:
        form = UserProfileForm(instance=user)
    return render(request, 'editing_profile.html', {'form': form})



# Профиль:
def profile_view(request):
    user = request.user
    return render(request, 'profile.html', {'user': user})



# Удаление профиля:
from .models import Comment
def delete_profile_view(request):
    if request.method == 'POST':

        user = request.user

        # Удаление всеч постов и комментариев пользователя:
        Post.objects.filter(author=user).delete()
        Comment.objects.filter(author=user).delete()

        user.delete()

        return redirect('BA:index')

    return render(request, 'confirm_delete.html')



# Создание поста:
from .forms import PostForm
def create_post_view(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('BA:index')  # Перенаправление на главную страницу
    else:
        form = PostForm()
    return render(request, 'create_post.html', {'form': form})



# Лайк:
def like_post_view(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user in post.likes.all():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    return redirect('BA:index')



# Мои посты:
def my_posts(request):
    posts = Post.objects.filter(author=request.user)
    return render(request, 'my_posts.html', {'posts': posts})



# Редактирование поста:
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if post.author != request.user:
        return redirect('BA:index')

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('BA:my_posts')
    else:
        form = PostForm(instance=post)

    return render(request, 'edit_post.html', {'form': form, 'post': post})


# Удаление поста:
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if post.author != request.user:
        return redirect('BA:index')

    if request.method == 'POST':
        post.delete()
        return redirect('BA:index')

    return render(request, 'delete_post.html', {'post': post})



# Создание комментария:
from .forms import CommentForm
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('BA:index')
    else:
        form = CommentForm()

    return render(request, 'add_comment.html', {'form': form, 'post': post})



# Редактирование комментария:
def edit_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    if comment.author != request.user:
        return redirect('BA:index')

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('BA:index')
    else:
        form = CommentForm(instance=comment)

    return render(request, 'edit_comment.html', {'form': form, 'comment': comment})



# Удаление комментария:
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    if comment.author != request.user:
        return redirect('BA:index')

    if request.method == 'POST':
        comment.delete()
        return redirect('BA:index')

    return render(request, 'delete_comment.html', {'comment': comment})



# Детали поста:
def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()  # Получение всех комментариев к посту
    return render(request, 'post_detail.html', {'post': post, 'comments': comments})



#Регистрация:
from django.shortcuts import redirect, render, get_object_or_404
from .forms import CustomUserCreationForm, CustomAuthenticationForm
def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])  # Хранение пароля в зашифрованном виде
            user.save()
            login(request, user)  # Автоматический вход после регистрации
            return redirect('BA:index')
        else:
            print(form.errors)  # Вывод ошибок формы для отладки
    else:
        form = CustomUserCreationForm()

    return render(request, 'registration/register.html', {'form': form})



# Авторизация:
def login_user(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('BA:index')
            else:
                form.add_error(None, 'Неверный логин или пароль.')
    else:
        form = CustomAuthenticationForm()

    return render(request, 'registration/login.html', {'form': form})



# Выход:
from django.contrib.auth import login, authenticate, logout
def logout_user(request):
    logout(request)
    return render(request,'registration/logged_out.html')

BP/BA/templates/add_comment.html
{% extends 'base.html' %}

{% block title %}<title>Добавить комментарий</title>{% endblock %}

{% block content %}
<h2>Добавить комментарий к посту: {{ post.title }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
</form>
<a href="{% url 'BA:index' %}">Назад</a>
{% endblock %}

BP/BA/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
        <h1>Здесь ты можешь делиться с миром чем-то новым!</h1>
        <nav>
            <ul>
                <li><a href="{% url 'BA:index' %}">Главная</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'BA:profile' %}">Профиль</a></li>
                <form method="post" action="{% url 'BA:logout' %}">
                    {% csrf_token %}
                    <button type="submit">Выйти</button>
                </form>
                {% else %}
                <li><a href="{% url 'BA:login' %}">Войти</a></li>
                <li>Нет аккаунта? <a href="{% url 'BA:register' %}">Зарегистрируйтесь!</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <div class="container">
        <main>
            {% block content %}
            <!-- Основное содержимое страницы будет здесь -->
            {% endblock %}
        </main>
    </div>

    <footer>
        <p>&copy; 2024 Design.pro</p>
    </footer>

</body>
</html>

BP/BA/templates/confirm_delete.html
{% extends "base.html" %}

{% block title %}<title>Удаление профиля</title>{% endblock %}
{% block content %}
   <form method="post">
       {% csrf_token %}
       <p>Вы уверены, что хотите удалить свой профиль? Это действие необратимо.</p>
       <button type="submit">Удалить профиль</button>
       <a href="{% url 'BA:profile' %}">Отмена</a>
   </form>
{% endblock %}

BP/BA/templates/create_post.html
{% extends "base.html" %}

{% block title %}<title>Создание поста</title>{% endblock %}
{% block content %}
<h1>Создать новый пост</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Опубликовать</button>
    </form>
    <a href="{% url 'BA:index' %}">Назад на главную</a>
{% endblock %}

BP/BA/templates/delete_comment.html
{% extends 'base.html' %}

{% block title %}<title>Удалить комментарий</title>{% endblock %}

{% block content %}
<h2>Вы уверены, что хотите удалить этот комментарий?</h2>
<p>{{ comment.content }}</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Удалить</button>
</form>
<a href="{% url 'BA:index' %}">Назад</a>
{% endblock %}

BP/BA/templates/delete_post.html
{% extends 'base.html' %}

{% block title %}<title>Удалить пост</title>{% endblock %}

{% block content %}
  <h2>Вы уверены, что хотите удалить пост "{{ post.title }}"?</h2>
  <form method="POST">
      {% csrf_token %}
      <button type="submit">Удалить</button>
  </form>
  <a href="{% url 'BA:index' %}">Назад</a>
{% endblock %}

BP/BA/templates/edit_comment.html
{% extends 'base.html' %}

{% block title %}<title>Редактировать комментарий</title>{% endblock %}

{% block content %}
<h2>Редактировать комментарий</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить изменения</button>
</form>
<a href="{% url 'BA:index' %}">Назад</a>
{% endblock %}

BP/BA/templates/edit_post.html
{% extends 'base.html' %}

{% block title %}<title>Редактировать пост</title>{% endblock %}

{% block content %}
  <h2>Редактировать пост: {{ post.title }}</h2>
  <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Сохранить изменения</button>
  </form>
  <a href="{% url 'BA:index' %}">Назад</a>
{% endblock %}

BP/BA/templates/editing_profile.html
{% extends "base.html" %}

{% block title %}<title>Редактирование профиля</title>{% endblock %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

BP/BA/templates/index.html
{% extends "base.html" %}

{% block title %}<title>Главная страница</title>{% endblock %}
{% block content %}
{% for post in page_obj %}
    <div class="post">
        <h2>{{ post.title }}</h2>
        <p>Автор: {{ post.author.username }}</p>
        <p>Дата: {{ post.created_at }}</p>
        <p>Количество комментариев: {{ post.comment_count }}</p>
        <p>{{ post.content }}</p>
        <p>
            <a href="{% url 'BA:like_post' post.id %}">Лайк</a> ({{ post.likes.count }})
        </p>
        <p>
            <a href="{% url 'BA:post_detail' post.id %}">Подробнее о посте</a>
        </p>
    </div>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Первая</a>
            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

BP/BA/templates/my_posts.html
{% extends 'base.html' %}

{% block title %}<title>Мои посты</title>{% endblock %}

{% block content %}
<h2>Мои посты</h2>

{% if posts %}
    <ul>
    {% for post in posts %}
        <li>
            <h3>{{ post.title }}</h3>
            <p>{{ post.content }}</p>
            <p>Автор: {{ post.author.username }} | Дата: {{ post.created_at }}</p>
            <a href="{% url 'BA:edit_post' post.id %}">Редактировать</a>
            <a href="{% url 'BA:delete_post' post.id %}">Удалить</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>У вас пока нет постов.</p>
{% endif %}

<a href="{% url 'BA:index' %}">Назад</a>
{% endblock %}

BP/BA/templates/post_detail.html
{% extends 'base.html' %}

{% block title %}<title>Детали поста</title>{% endblock %}

{% block content %}
<h2>{{ post.title }}</h2>
<p>{{ post.content }}</p>

<h3>Комментарии:</h3>
<ul>
    {% for comment in comments %}
    <li>
        {{ comment.content }} - <strong>{{ comment.author.username }}</strong>
        {% if comment.author == user %}
            <a href="{% url 'BA:edit_comment' comment.id %}">Редактировать</a>
            <a href="{% url 'BA:delete_comment' comment.id %}">Удалить</a>
        {% endif %}
    </li>
    {% empty %}
    <li>Нет комментариев.</li>
    {% endfor %}
</ul>

<a href="{% url 'BA:add_comment' post.id %}">Добавить комментарий</a>
<a href="{% url 'BA:index' %}">Назад</a>
{% endblock %}

BP/BA/templates/profile.html
{% extends "base.html" %}

{% block title %}<title>Профиль</title>{% endblock %}
{% block content %}
<p><strong>Имя:</strong> {{ user.first_name }}</p>
<p><strong>Фамилия:</strong> {{ user.last_name }}</p>
<p><strong>Отчество:</strong> {{ user.middle_name }}</p>
<p><strong>Логин:</strong> {{ user.username }}</p>
{% if user.avatar %}
    <p><strong>Аватар:</strong></p>
    <img src="{{ user.avatar.url }}" alt="Аватар" style="width: 100px; height: 100px;">
{% endif %}
<p><strong>Биография:</strong> {{ user.bio }}</p>
<a href="{% url 'BA:editing_profile' %}">Редактирование профиля</a>
<a href="{% url 'BA:delete_profile' %}">Удалить профиль</a>
<a href="{% url 'BA:create_post' %}">Создать пост</a>
<a href="{% url 'BA:my_posts' %}">Мои посты</a>
{% endblock %}